apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: multi-arch-build
spec:
  params:
    - name: git-repo
      type: string
      description: Repository URL to clone from.
    - name: git-revision
      type: string
      default: main
      description: Revision to checkout. (branch, tag, sha, ref, etc...)
    - name: output-image
      type: string
      description: Reference of the image the pipeline will produce.
    - name: platforms
      type: array
      description: Target platforms for the image build.
      default:
        - linux/amd64
        - linux/arm64
  workspaces:
    - name: shared
  tasks:
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.git-repo)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared
    
    - name: build-images
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: buildah
      matrix:
        params:
          - name: PLATFORM
            value: $(params.platforms)
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: STORAGE_DRIVER
          value: vfs
      workspaces:
        - name: source
          workspace: shared
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: multi-arch-build-run
spec:
  pipelineRef:
    name: multi-arch-build
  params:
    - name: git-repo
      value: https://github.com/jkhelil/minimal-container
    - name: git-revision
      value: main
    - name: output-image
      value: quay.io/jkhelil/minimal-container-matrix1
    - name: platforms
      value:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
  workspaces:
    - name: shared
      persistentVolumeClaim:
        claimName: tekton-build
