apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: multi-arch-build
spec:
  params:
    - name: git-repo
      type: string
      description: Repository URL to clone from.
    - name: git-revision
      type: string
      default: main
      description: Revision to checkout. (branch, tag, sha, ref, etc...)
    - name: output-image
      type: string
      description: Reference of the image the pipeline will produce.
    - name: amd64-platform
      type: string
      description: Platform to use for amd64 remote builds
      default: linux/amd64
    - name: arm64-platform
      type: string
      description: Platform to use for arm64 remote builds
      default: linux/arm64
    - name: ppc64le-platform
      type: string
      description: Platform to use for ppc64le remote builds
      default: linux/ppc64le
    - name: s390x-platform
      type: string
      description: Platform to use for s390x remote builds
      default: linux/s390x
  workspaces:
    - name: shared
  tasks:
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.git-repo)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared
    - name: build-images
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: buildah
      matrix:
        include:
          # While this is possible to do, we build amd64 in-cluster instead.
          #  In order to build amd64 remotely, uncomment this and disable
          #  the in-cluster task by setting params.build-amd-in-cluster to false
          # - name: amd64
          #   params:
          #     - name: IMAGE
          #       value: $(params.output-image)-amd64
          #     - name: PLATFORM
          #       value: $(params.amd64-platform)
          - name: arm64
            params:
              - name: IMAGE
                value: $(params.output-image)-arm64
              - name: PLATFORM
                value: $(params.arm64-platform)
          - name: ppc64le
            params:
              - name: IMAGE
                value: $(params.output-image)-ppc64le
              - name: PLATFORM
                value: $(params.ppc64le-platform)
          - name: s390x
            params:
              - name: IMAGE
                value: $(params.output-image)-s390x
              - name: PLATFORM
                value: $(params.s390x-platform)
      params:
        - name: STORAGE_DRIVER
          value: vfs
      workspaces:
        - name: source
          workspace: shared
