apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simple-build-pipeline
spec:
  params:
    - name: git-repo
      type: string
      description: Repository URL to clone from.
    - name: git-revision
      type: string
      default: main
      description: Revision to checkout. (branch, tag, sha, ref, etc...)
    - name: output-image
      type: string
      description: Reference of the image the pipeline will produce.
  workspaces:
    - name: shared
  tasks:
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.git-repo)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared
    - name: build-images
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: buildah
      matrix:
        params:
          - name: IMAGE
            value:
              - "$(params.output-image)-arm64"
              - "$(params.output-image)-ppc64le"
              - "$(params.output-image)-s390x"
      params:
        - name: STORAGE_DRIVER
          value: vfs
      workspaces:
        - name: source
          workspace: shared
    - name: build-image-index
      runAfter:
        - build-images
      taskRef:
        kind: Task
        name: buildah
      params:
        - name: STORAGE_DRIVER
          value: vfs
        - name: IMAGE
          value: $(params.output-image)
        - name: SCRIPT
          value: |
            buildah manifest create $(params.output-image)
            buildah manifest add $(params.output-image) docker://$(params.output-image)-arm64
            buildah manifest add $(params.output-image) docker://$(params.output-image)-ppc64le
            buildah manifest add $(params.output-image) docker://$(params.output-image)-s390x
            buildah manifest push --all $(params.output-image) docker://$(params.output-image)
      workspaces:
        - name: source
          workspace: shared
  results: 
    - name: IMAGE_URL
      description: 'URL of the built image'
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      description: 'Digest of the built image'
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    - name: CHAINS-GIT_URL
      description: ''
      value: "$(tasks.git-clone.results.url)"
    - name: CHAINS-GIT_COMMIT
      description: ''
      value: "$(tasks.git-clone.results.commit)"
   